name: Build on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    name: Windows (Qt ${{ matrix.qt_version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            qt_version: 5.15.2
          - os: windows-latest
            qt_version: 6.8.3
          - os: windows-latest
            qt_version: 6.10.3

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ matrix.qt_version }}
        cache: true

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTING=YES

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      env:
        QT_QPA_PLATFORM: offscreen
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -V
