name: Build on Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    name: Linux (${{ matrix.qtpackage }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - qtpackage: qtbase5-dev
            qt_install_cmd: sudo apt update -y && sudo apt install -y libefivar-dev libefiboot-dev qtbase5-dev
          - qtpackage: qt6-base-dev
            qt_install_cmd: sudo apt update -y && sudo apt install -y libefivar-dev libefiboot-dev qt6-base-dev

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: ${{ matrix.qt_install_cmd }}

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTING=YES

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      env:
        QT_QPA_PLATFORM: offscreen
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -V
