name: Build on FreeBSD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
         submodules: true
    # Configure and build
    - uses: vmactions/freebsd-vm@v1
      with:
        release: 14.1
        usesh: true
        prepare: |
          pkg install -y cmake qt5
        run: |
          uname -a
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING=YES
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # Test
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
